# Generated by Django 4.1.7 on 2023-04-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_plant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watering',
            name='amount',
            field=models.IntegerField(default=100),
        ),
    ]
